version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: youtube
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      DB_USER: postgres
      DB_PASSWORD: password
      DB_NAME: youtube
      DB_HOST: db
      DB_PORT: 5432
      YOUTUBE_API_KEY: <API_KEY>
volumes:
  postgres-data:
